CREATE TABLE IF NOT EXISTS `EMFUser` (
  `user_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `checked_in` BOOLEAN NOT NULL DEFAULT 0,
  `UID` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `UID` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `EMFUser`
  ADD CONSTRAINT `emfuser_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `User` (`UID`) ON DELETE SET NULL ON UPDATE SET NULL;

